### ISSUE TITLE
Merging of scenarios and states

### ISSUE THREAD

**Issue by jamesscottbrown** [dsi-icl/ove#11]
This issue summarises a conversation between me, @senakafdo and @oserban.

The current distinction between ``scenario`` and ``state`` is confusing: a ``scenario`` is essentially a ``state`` that has been saved and given a name, but with minor differences that should be eliminated.

The ``scenario`` should be renamed to something like ``savedState`` and consist of three elements: a ``state`` object, a ``name``, and a ``preload`` boolean that specifies whether or not content should render before the corresponding controller has loaded.

When a ``section`` is created, it should be optionally passed a ``savedState`` object (rather than being passed one/both/neither of ``state`` and ``scenario``). If ``preload == true``, then this should be immediately loaded; if ``preload == false``,  then this should not be loaded until the corresponding control page is loaded in a web browser.

Additionally, there should be an API route that allows a ``savedState`` to be loaded into a specified section (perhaps ``<app>/load?oveSectionId=0&stateName=foo``). There is currently a somewhat similar API route at ``<app>/control.html?oveSectionId=0&scenario=foo``, but this URL must be loaded in a web browser so that some JavaScript code can send broadcast messages; the new route should cause these messages to be sent directly from the server.

**Comment by senakafdo** [comment]
@jamesscottbrown, as discussed agree fully on merging the concepts of `state` and `scenario` which are very confusing right now. However, the API probably needs to have a better naming system instead of calling everything a `savedState`.

Let me take a step-by-step approach to get to the point, :-).

First of all, we will actually have `savedState` which is a part of each application's configuration. This can be used to load samples or well known scenarios into the observatory. This is also why I initially called them scenarios. Please note that each application can have more than one such well known scenarios.

Secondly, there is the state that you can pass into an application when initialising it. Currently you can pass one state, but ideally you could be passing more than one state if the end user is presented with a selection of scenarios they could chose from.

Next, the user should have an option of preloading an application either with the state that you just created during initialisation or with an existing `savedState`. Also, if the user is passing a state object when creating a section for the sole purpose of loading the application with that state, they may not want to give it a name to make their URL straightforward.

So, all in all, I find that the most optimum model should be something like:
`scenario: {name:"", state:{}, preload:bool}`
Then the user has the following 5 options:
- Provide a state with a name and preload it
- Provide a state with a name and not preload it
- Provide a state without a name and preload it by default
- Provide a name without a state and preload a saved state by default
- Not provide anything at all

If we think it is necessary, we can support a 6th option where the user can provide more than one scenario when creating a section. The structure would then look like:
`scenarios: [{name:"", state:{}, preload:bool},...]`
There will be one rule if we are to support this. You can only have one scenario block which doesn't have either of name/state or has preload set to true.

Assuming that we thought it was necessary to support the 6th option above, and if we wanted to make our rules a bit more obvious, a better model would be:
`scenarios:{
    load:{name:"", state:{}},
    cache:[{name:"", state:{}},...]
}`
Note that I've changed `preload` to `load` to avoid a further confusion between `preload` vs `cache`. Also note that I'm calling the collection of scenarios `cache` rather than `save` to avoid a further confusion of states already saved on the disk vs states populated during the creation of a section.

Now, if we were to avoid the original confusion between `scenario` and `state` and have a single model, a slightly modified version of the above would look like:
`state:{
    load:"name" || {},
    cache:{"name":{},...}
}`
I will go ahead and make this change to the design. But, if you or anyone else has a better proposal than mine, please feel free to suggest.

**Comment by miguems** [comment]
Hi @senakafdo, I liked @jamesscottbrown proposal more. I think it is easy to understand and cover most use cases. I cannot see what is the benefit of the extra bit of complication that you propose.

**Comment by senakafdo** [comment]
@miguems, both were models that I proposed actually (though @jamesscottbrown documented it on this issue following a chat between the two of us and @oserban). 

Today morning, @jamesscottbrown and I decided to go for the latest model that I proposed because of the following reasons:
- The API can be used to provide more than one state to be cached such that subsequent requests can make use of it.
- An explicit flag for `preload=true` is not necessary since the `load` instruction is optional and when present always means `preload=true`.

We also changed `state` to `states` to reflect what the API does more accurately.

I was chatting on my comment above with @jamesscottbrown, and it is perhaps the way that I explained it that made it sound complicated. So, let me explain in it a way that it can be easily understood.

We have the following combinations of providing state information when creating a section:
1. Preload a state saved on the filesystem based config: `"states": {"load": "name"}`
1. Preload a new state which will not be cached: `"states": {"load": {...}}`
1. Preload a new state which will not be cached but cache few additional states for later use: `"states":{"load": {...}, "cache": {"state1": {...}, "state2": {...}, ...}}`
1. Cached few states and preload one of them or any state already saved on the filesystem based config as the current: `"states": {"load": "name", "cache": {"state1": {...}, "state2": {...}, ...}}`
1. Cached few states for later use but preload nothing: `"states": {"cache": {"state1": {...}, "state2": {...}, ...}}`
1. The final option is to not provide any state element, which will mean nothing will be preloaded and nothing will be cached for future use.

Despite the many combinations, the most popular API calls would be:
- `"states": {"load": {...}}`
- `"states": {"cache": {"state1": {...}}`
- `"states": {"load": "name"}`

So, there will be absolutely no confusion for the end user.

We will be documenting this API and our SDKs will also make it much easier to someone to understand the interaction patterns, so we decided to proceed with it.

**Comment by senakafdo** [comment]
@miguems, I also want to add that the motivation here is to give the end user a very straightforward API to perform their required operations. And, at the same time we have the extensibility we require for any advanced usecases. So, when we document this, we will focus on explaining it as below:
- Load a new state: `"states": {"load": {...}}`
- Load an existing state: `"states": {"load": "name"}`
- Cache one or more states for later use: `"states": {"cache": {"state1": {...}, "state2": {...}}`
