### ISSUE TITLE
Errors loading base URLs of apps

### ISSUE THREAD

**Issue by jamesscottbrown** [dsi-icl/ove#33]
The ``index.html`` file of OVE apps contains ``_OVEHOST_`` and ``_OVETYPE_`` placeholders/constants, which [are replaced](https://github.com/dsi-icl/ove/blob/master/packages/ove-app-base/src/index.js#L94) when requests for this file are served by ``index.js`` of ``ove-app-base``.

However, if a request is made for the base URL of an app (e.g. ``http://localhost:8086/`` rather than ``http://localhost:8086/index.html``), the ``index.html`` page is still served, but without this substitution being made, resulting in potentially confusing errors.

**Comment by senakafdo** [comment]
Thought about this in detail. The `/` URL of an app is not somewhere someone would be interested in finding details about the application and it also can be fairly confusing when we display links to viewers/controllers, especially when the systems are clustered etc. To avoid this hassle, I decided to keep things simple and simply serve `/index.html` which is what someone would expect in this case. The default view for an app is its `view.html`, so that is what this renders.

**Comment by jamesscottbrown** [comment]
> The default view for an app is its view, so that is what this renders.

It isn't *quite* what it renders, because the  ``_OVEHOST_`` and ``_OVETYPE_`` placeholders are not replaced.

Why not redirect to ``/index.html`` instead?

**Comment by senakafdo** [comment]
> Why not redirect to /index.html instead?

That's exactly what 4dbdee6 does, :). `/` routes to `/index.html` within node.js, which is slightly better getting the browser to respond to a 301.

When I said default view for an app is its view, that's what you get when you use /index.html instead of /view.html or /control.html.
