### ISSUE TITLE
Code Review for Videos App

### ISSUE THREAD

**Issue by davidbirchwork** [dsi-icl/ove#60]
A few thoughts from reading through the code: 

-  Index.js
    -  all config constants should be stored away from code (350ms, 15%) in a settings file and read. 
    -  no error messages are sent on the get API (e.g. unless exception is thrown it will return a 200) this may be by design? 
    -  next parameter appears never to be used 
    -  variables should be defined at the top of the file
    -  is there anyway to simplify this? “(typeof req.query.loop != 'undefined' &&(JSON.parse(String(req.query.loop).toLowerCase()) == true))”
-  common/videos.js 
    - use of default case for seekto may cause issues – better to include a case and handle the error 
    - your 15% threshold is here again, can this be read from a settings file or should it be part of the state? 
    -  15% is arbitrary and for long (e.g. hour long) videos it should be much lower – so we should give control to the user / player? 
-  you have 3 different files named videos.js (!)
- There is limited commenting throughout the codebase ;-)

**Comment by jamesscottbrown** [comment]
> is there anyway to simplify this? “(typeof req.query.loop != 'undefined' && (JSON.parse(String(req.query.loop).toLowerCase()) == true))”

You could assign the value of ``(JSON.parse(String(req.query.loop).toLowerCase()) == true)`` to a variable/constant that describes what it actually means (``loopEnabled``?).

Similarly, there's [a statement](https://github.com/dsi-icl/ove/blob/master/packages/ove-app-videos/src/index.js#L19) that checks for ``JSON.stringify(bufferStatus[m.sectionId]) !== JSON.stringify({})``,  and [another](https://github.com/dsi-icl/ove/blob/master/packages/ove-app-videos/src/index.js#L12) that checks for ``JSON.stringify(bufferStatus[m.sectionId]) === JSON.stringify({})``.

Instead you could define ``const bufferIsEmpty = (JSON.stringify(bufferStatus[m.sectionId]) === JSON.stringify({}))`` and use ``bufferIsEmpty`` in both tests.

**Comment by senakafdo** [comment]
@davidbirchwork, thanks.

To start off, the pattern of having three files is deliberate. There are viewer specific JS, controller specific JS and also common JS. I believe that structure is easily understood. Apart from this, some apps may have other directories such as `players` in the videos app.

The get on the index.js does not have a situation apart from seek time being non-numeric and the loop setting not being a boolean value. The regular expression of the route blocks everything else. I can enforce type checking, but that is also possibly an overhead since the API is well documented. In general a get operation can only fail either if the resource was not available or a query is improperly formatted. I don't think I should be introducing any additional state checks to validate whether the video exists etc, which will introduce roundtrip overheads between clients/server.

Variables are defined within the nearest scope in modern JS (i.e. let/const) and top-level definitions are generally discouraged. But, for a variable in a broader scope, you could define it right at the top or closer to a function that it is used. My personal view is that the latter improves readability since all variables are prefixed and their purpose is easily understood.

I will look into the rest of the issues as I agree that they are pitfalls in the code.

@jamesscottbrown, introducing less/more variables to improve readability is actually a preference, :). I do realise that it may be harder for someone to easily understand what this implies. So, I will not only introduce comments but will also breakdown complex operations such that they can be easily understood.

**Comment by davidbirchwork** [comment]
@senakafdo @jamesscottbrown yep i gathered the rational for the 3 identical files, i just wondered if it would be clearer to call them x_control.js  x_view.js ... or  similar to differentiate in documentation and usage. This is the standard in MVC in .net 

@senakafdo the variable in question (`bufferStatus`) is used in both the method above and below its definition hence suggest defined at top level due to broader scope

**Comment by senakafdo** [comment]
Note to self: Should also review the uses of let/const/var across the board. I believe there seems to be some misuses.
