### ISSUE TITLE
OVE Ideal Coordinate System

### ISSUE THREAD

**Issue by davidbirchwork** [dsi-icl/ove#83]
**Current Situation**:
 - Everything in OVE works in pixels
 - Configurations for spaces and screens are specified in pixels
 - We have a bezel correction service which creates new configurations specified in pixels 

**Issues**:
 - When applying bezel correction sections specified in pixels may now 
      - lose content between monitors
      - no longer start at bezels 

**Proposed solution**:
 - Introduce an idealised coordinate space (e.g. 0..1 or better 0..360 for easy divisibility) - "Viz coordinate system"
 - Specify spaces with 
       - ideal pixel width and height
       - the idealised "Viz Coordinates" they represent (e.g. 0.25 to 0.50 in X) (can be calculated from uncorrected pixels)
       - the bezel correction offset  parameters 
- Users should never specify their sections in pixels but rather in "Viz" space
- Within OVE core a mapping is made between "Viz" space and pixel space. 
- This mapping should be done within OVE core .js to respect certain rules which can be set default per app and overridden by users. 
    - snap this section to ideal percentage (so small slivers of apps are not on odd screens)
    - do not lose pixels (so that letters in title images are not lost)
    - respect aspect ratio
    - this mapping may require a solver 
- States should be saved in idealised coordinates

**Comment by senakafdo** [comment]
I was thinking about this in detail.

**Improvements to Clients.json**
So, first of all, we have a clear limitation in the way we define bezel corrected and non-bezel corrected client configurations. We cannot be having 2 separate spaces for these, we need to be having one, because they both refer to the same space, to start with.

**viz coordinates - not convinced that this works**
That said, while the idea of `viz coordinates` is great, if the end user wants to perfectly snap their content to grids, they should either configure a rule, or they should know precisely what the percent-wise or 0...360-vise coordinates they should be using to ensure their content is loaded at the right locations. The apps are not space-dependent, so they should never need to be requesting viz coordinates from a space or client etc. This is why the pixel-space works perfectly for content, since there is nothing that binds a visualisation to a specific-space. Therefore, what the viz coordinates seem to achieve is providing the users with an alternative numbering system that is 1:x with the pixel coordinates from the bezel-uncorrected range. And, therefore, I don't see any advantage in doing this.

**rules**
I fully support the idea of the rules. The starting point for the end user would be a space which has two sets of coordinates, bezel corrected and bezel-uncorrected. First of all, they can chose what they want on a section-section basis. Once they chose, they can request what they specifically want and then a solver would produce an ideal configuration.

**laying out content - GUI tool**
Even though the concept of viz coordinates is out, the end user must not be burdened with regards to knowing precisely where to place their content and do calculations based on pixel heights/widths. They should instead be able to work with a grid and select (a) where on that grid they would place significant blocks of what they are building and then (b) subsequently overlay that with additional sections that do not perfectly fit that grid. They will never use any kind of coordinate system for (a) in my opinion, but use the rows/columns to decide on how/where to place things. But, for (b), they will certainly want very precise placement and that's where they would opt for pixel coordinates, because that's exactly what they are after at that point. 

We must keep in mind that the users will not be typing any of this. They will be using a GUI that will help them position their content on the space, and the DO has sections that will move back and forth based on where the user wants to place their content.

**SDKs**
Users need not always use the GUI once they have put together a template, since they should at that point be able to load it into an SDK and then arrange their content within those sections or re-position them with a few lines of Python code.

So, apart from a 'service' (I mean the combination of UI/API/SDK etc) to evaluate the rules and help OVE produce a layout, there is really no end-user involvement in deciding on how and where to place their content.

**Coordinates within an app - is already properly dealt with**
All alignment of content within an app is relative to section height/width and uses viewport-based coordinates (vw/vh). This makes the content fit any device or any size of section. We should not be replacing this with our own coordinate system or a grid - if we do that, apps (same applies to visualisations) will only work in specific layouts.

**Summary**
First of all, we need to improve the Clients.json to support both bezel-(un)corrected layouts. Then,
I think that we should not be debating about this before we have seen what the GUI tool will be doing.

**Comment by davidbirchwork** [comment]
Thanks @senakafdo some good points here. 

I'd suggest we combine both approaches and provide helpers or rules such as a grid in Viz Space 

Benefits of an abstract coordinate space (i.e. not pixels):
 - avoids visualisations being created with dependance on any one space and its resolutions (only dependence is aspect ratio)
 - infinitely divisible into grids 
 - is transferable between spaces 
 - enables rule based transformation to bezel correction and other features (e.g. drag and resize a group of sections around?)
 - hides these rules and transformations from the user

**Comment by jamesscottbrown** [comment]
>  But, for (b), they will certainly want very precise placement and that's where they would opt for pixel coordinates, because that's exactly what they are after at that point.

I'm not sure that pixel coordinates necessarily are "exactly what they are after": I think that relative coordinates may be more convenient to use.

> arrange their content within those sections

As I  understand it, content isn't *arranged within sections* as such: sections are arranged/positioned on the screen, and then content is loaded into these fixed section positions.

> We must keep in mind that the users will not be typing any of this. They will be using a GUI

I think that the GUI should allow the user to enter a precise position and size for a section in some coordinate system (probably the proportional coordinate system), as an alternative to directly dragging a rectangle or shifting it using arrow keys. A user will *not necessarily* be typing any of this, but we should *allow* them to if they wish.

It may also be helpful to provide the user with the ability to display a rule [in the sense of ruler or scale, not in the sense of an instruction], which would also expose a coordinate system.

> "they should at that point be able to load it into an SDK and then arrange their content within those sections or re-position them with a few lines of Python code . . . there is really no end-user involvement in deciding on how and where to place their content"

I don't understand: this sounds like a contradiction to me. Repositioning things with a few lines of code sounds like direct end-user control over where to place content.

**Comment by oserban** [comment]
This is how I see the layout problem at the moment and I am nudging towards an external service. The OVE should only place sections at pixel level (bezel corrected or not). 

When an App is deployed OVE should negotiate the layout service the exact placement of components. 

While the App layout will be environment independent, the output of the layout service will be OVE dependent.

In this approach you let the user decide/describe his layout. When you will deploy your app to the OVE you will have to pass along a state (which you currently do) + a layout file which describes how you will use:

- which layout model you will use (static, bevel corrected, grid, percents, force-based, graph-based, etc)
- the layout model for each section (I can see this similar to something you do in css)

I can see some users being satisfied with a very loose layout such as: the width of component x needs to be 3 times the width of component y. 

With this model if a user/developer is not satisfied with any layout option available, he can create a custom app layout.

Plus the layout manager can can couple sections as well: e.g. the legend of a map move together with the map, if the layout accepts movement of sections
